name        = 'h1st0ry'
license     = 'MIT'
licenselink = 'https://github.com/m0t0k1ch1/h1st0ry/blob/master/LICENSE'
description = 'A minimal, responsive blogging theme for Hugo built with Bulma.'
homepage    = 'https://github.com/m0t0k1ch1/h1st0ry'
tags        = ['blog', 'bulma', 'clean', 'disqus', 'google analytics', 'light', 'minimal', 'responsive', 'simple', 'syntax highlighting', 'white']
features    = ['math rendering by katex', 'responsive design by bulma', 'share buttons by addthis', 'shortcode for github', 'syntax highlighting by chroma']
min_version = '0.55'

[author]
    name     = 'm0t0k1ch1'
    homepage = 'https://m0t0k1ch1st0ry.com/author'
